import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import { CustomCursor, Header } from "@/components";
import NextTopLoader from "nextjs-toploader";
import { Analytics } from "@vercel/analytics/react";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rishabh Singh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} bg-[#F8EEEC] dark:bg-[#0E0C0A]`}
      >
        <Providers>
          <CustomCursor />
          <Header />
          <NextTopLoader showSpinner={false} color="#8b5cf6" zIndex={999} />
          {children}
          <Analytics />
        </Providers>
      </body>
    </html>
  );
}
